### ISSUE TITLE
Website improvements TODO

### ISSUE THREAD

**Issue by ceball** [ioam/parambokeh#28]
* [ ] put full-sized logo with wordmark on homepage
* [ ] add param(bokeh) style (currently just default nbsite)
* [ ] make sure logo is transparent, scalable, etc. if appropriate for each version
* [ ] add gallery
* [ ] name user guide pages with numbers (but see https://github.com/ioam/nbsite/issues/18)
* [ ] deploy website for commits to master to an alternative address [testing: https://ioam-docs.github.io/parambokeh-master/)
* [ ] deploy website for PRs to an alternative address
* [ ] indicate/allow selection of version on website (depends on auto versioning)
